CREATE TABLE "accounts" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL,
	"name" text NOT NULL,
	"type" text DEFAULT 'cash' NOT NULL,
	"currency" text DEFAULT 'UZS' NOT NULL,
	"initial_balance" numeric(18, 2) DEFAULT 0 NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "accounts_type_check" CHECK ("accounts"."type" in ('cash', 'uzcard', 'humo', 'bank', 'ewallet', 'other')),
	CONSTRAINT "accounts_currency_check" CHECK ("accounts"."currency" in ('UZS', 'USD', 'EUR'))
);
--> statement-breakpoint
CREATE TABLE "audit_logs" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "audit_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" integer,
	"actor_role" text DEFAULT 'USER' NOT NULL,
	"action" text NOT NULL,
	"entity" text NOT NULL,
	"entity_id" integer,
	"outcome" text NOT NULL,
	"request_id" text NOT NULL,
	"ip_hash" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "audit_outcome_check" CHECK ("audit_logs"."outcome" in ('success', 'denied', 'failed')),
	CONSTRAINT "audit_actor_role_check" CHECK ("audit_logs"."actor_role" in ('USER', 'ADMIN'))
);
--> statement-breakpoint
CREATE TABLE "budgets" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL,
	"category_id" integer,
	"month" text NOT NULL,
	"amount" numeric(18, 2) NOT NULL,
	"rollover" boolean DEFAULT false NOT NULL,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "budgets_amount_check" CHECK ("budgets"."amount" > 0),
	CONSTRAINT "budgets_month_check" CHECK ("budgets"."month" ~ '^\d{4}-(0[1-9]|1[0-2])$')
);
--> statement-breakpoint
CREATE TABLE "categories" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL,
	"parent_id" integer,
	"name" text NOT NULL,
	"type" text NOT NULL,
	"icon" text DEFAULT '•' NOT NULL,
	"color" text,
	"is_essential" boolean DEFAULT false NOT NULL,
	"is_system" boolean DEFAULT false NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "categories_type_check" CHECK ("categories"."type" in ('income', 'expense'))
);
--> statement-breakpoint
CREATE TABLE "debt_payments" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL,
	"debt_id" integer NOT NULL,
	"amount" numeric(18, 2) NOT NULL,
	"date" date NOT NULL,
	"note" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "debt_payments_amount_check" CHECK ("debt_payments"."amount" > 0)
);
--> statement-breakpoint
CREATE TABLE "debts" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL,
	"direction" text NOT NULL,
	"person_name" text NOT NULL,
	"amount" numeric(18, 2) NOT NULL,
	"remaining_amount" numeric(18, 2) NOT NULL,
	"due_date" date,
	"note" text,
	"status" text DEFAULT 'active' NOT NULL,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "debts_direction_check" CHECK ("debts"."direction" in ('i_owe', 'owed_to_me')),
	CONSTRAINT "debts_amount_check" CHECK ("debts"."amount" > 0 and "debts"."remaining_amount" >= 0 and "debts"."remaining_amount" <= "debts"."amount"),
	CONSTRAINT "debts_status_check" CHECK ("debts"."status" in ('active', 'settled'))
);
--> statement-breakpoint
CREATE TABLE "expected_incomes" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL,
	"source_name" text NOT NULL,
	"amount" numeric(18, 2),
	"min_amount" numeric(18, 2),
	"max_amount" numeric(18, 2),
	"expected_date" date NOT NULL,
	"frequency" text DEFAULT 'monthly' NOT NULL,
	"certainty" text DEFAULT 'exact' NOT NULL,
	"account_id" integer,
	"category_id" integer,
	"is_active" boolean DEFAULT true NOT NULL,
	"note" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "expected_certainty_check" CHECK ("expected_incomes"."certainty" in ('exact', 'estimated')),
	CONSTRAINT "expected_frequency_check" CHECK ("expected_incomes"."frequency" in ('once', 'weekly', 'monthly', 'yearly')),
	CONSTRAINT "expected_amount_check" CHECK (("expected_incomes"."certainty" = 'exact' and "expected_incomes"."amount" > 0) or ("expected_incomes"."certainty" = 'estimated' and "expected_incomes"."min_amount" > 0 and "expected_incomes"."max_amount" >= "expected_incomes"."min_amount"))
);
--> statement-breakpoint
CREATE TABLE "financial_snapshots" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL,
	"snapshot_date" date NOT NULL,
	"total_balance" numeric(18, 2) DEFAULT 0 NOT NULL,
	"income" numeric(18, 2) DEFAULT 0 NOT NULL,
	"expense" numeric(18, 2) DEFAULT 0 NOT NULL,
	"savings_rate" numeric(6, 4) DEFAULT 0 NOT NULL,
	"health_score" integer DEFAULT 0 NOT NULL,
	"meta" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "snapshots_health_check" CHECK ("financial_snapshots"."health_score" between 0 and 100)
);
--> statement-breakpoint
CREATE TABLE "goal_contributions" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL,
	"goal_id" integer NOT NULL,
	"amount" numeric(18, 2) NOT NULL,
	"date" date NOT NULL,
	"note" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "goal_contributions_amount_check" CHECK ("goal_contributions"."amount" > 0)
);
--> statement-breakpoint
CREATE TABLE "goals" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL,
	"name" text NOT NULL,
	"icon" text DEFAULT '🎯' NOT NULL,
	"target_amount" numeric(18, 2) NOT NULL,
	"saved_amount" numeric(18, 2) DEFAULT 0 NOT NULL,
	"target_date" date,
	"monthly_contribution" numeric(18, 2) DEFAULT 0 NOT NULL,
	"account_id" integer,
	"status" text DEFAULT 'active' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "goals_amount_check" CHECK ("goals"."target_amount" > 0 and "goals"."saved_amount" >= 0 and "goals"."saved_amount" <= "goals"."target_amount" and "goals"."monthly_contribution" >= 0),
	CONSTRAINT "goals_status_check" CHECK ("goals"."status" in ('active', 'reached'))
);
--> statement-breakpoint
CREATE TABLE "idempotency_keys" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "idempotency_keys_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" integer NOT NULL,
	"key" text NOT NULL,
	"scope" text NOT NULL,
	"status" text DEFAULT 'processing' NOT NULL,
	"result_id" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	CONSTRAINT "idempotency_status_check" CHECK ("idempotency_keys"."status" in ('processing', 'completed'))
);
--> statement-breakpoint
CREATE TABLE "notifications" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL,
	"type" text NOT NULL,
	"severity" text DEFAULT 'info' NOT NULL,
	"title" text NOT NULL,
	"body" text NOT NULL,
	"ref_date" date,
	"amount" numeric(18, 2),
	"meta" jsonb,
	"read_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "notifications_severity_check" CHECK ("notifications"."severity" in ('info', 'success', 'warning', 'critical'))
);
--> statement-breakpoint
CREATE TABLE "pending_drafts" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL,
	"chat_id" bigint,
	"message_id" integer,
	"kind" text DEFAULT 'transaction' NOT NULL,
	"payload" jsonb NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"resolved_at" timestamp with time zone,
	"expires_at" timestamp with time zone,
	CONSTRAINT "pending_drafts_status_check" CHECK ("pending_drafts"."status" in ('pending', 'processing', 'confirmed', 'cancelled', 'expired'))
);
--> statement-breakpoint
CREATE TABLE "recurring_expenses" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL,
	"category_id" integer,
	"account_id" integer,
	"name" text NOT NULL,
	"amount" numeric(18, 2),
	"min_amount" numeric(18, 2),
	"max_amount" numeric(18, 2),
	"due_day" integer DEFAULT 1 NOT NULL,
	"frequency" text DEFAULT 'monthly' NOT NULL,
	"is_mandatory" boolean DEFAULT true NOT NULL,
	"certainty" text DEFAULT 'exact' NOT NULL,
	"next_due_date" date NOT NULL,
	"reminder_days_before" integer DEFAULT 1 NOT NULL,
	"paid_through" date,
	"is_active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "recurring_due_day_check" CHECK ("recurring_expenses"."due_day" between 1 and 28),
	CONSTRAINT "recurring_certainty_check" CHECK ("recurring_expenses"."certainty" in ('exact', 'estimated')),
	CONSTRAINT "recurring_frequency_check" CHECK ("recurring_expenses"."frequency" in ('once', 'weekly', 'monthly', 'yearly')),
	CONSTRAINT "recurring_amount_check" CHECK (("recurring_expenses"."certainty" = 'exact' and "recurring_expenses"."amount" > 0) or ("recurring_expenses"."certainty" = 'estimated' and "recurring_expenses"."min_amount" > 0 and "recurring_expenses"."max_amount" >= "recurring_expenses"."min_amount"))
);
--> statement-breakpoint
CREATE TABLE "security_events" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "security_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" integer,
	"event" text NOT NULL,
	"severity" text DEFAULT 'warning' NOT NULL,
	"request_id" text NOT NULL,
	"ip_hash" text,
	"metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "telegram_updates" (
	"update_id" bigint PRIMARY KEY NOT NULL,
	"user_id" integer,
	"processed_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "transactions" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL,
	"account_id" integer NOT NULL,
	"to_account_id" integer,
	"category_id" integer,
	"type" text NOT NULL,
	"amount" numeric(18, 2) NOT NULL,
	"currency" text DEFAULT 'UZS' NOT NULL,
	"date" date NOT NULL,
	"note" text,
	"source" text DEFAULT 'miniapp' NOT NULL,
	"recurring_id" integer,
	"expected_income_id" integer,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"deleted_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "transactions_type_check" CHECK ("transactions"."type" in ('income', 'expense', 'transfer')),
	CONSTRAINT "transactions_amount_check" CHECK ("transactions"."amount" > 0),
	CONSTRAINT "transactions_currency_check" CHECK ("transactions"."currency" in ('UZS', 'USD', 'EUR'))
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" serial PRIMARY KEY NOT NULL,
	"telegram_id" bigint,
	"first_name" text DEFAULT 'Foydalanuvchi' NOT NULL,
	"last_name" text,
	"username" text,
	"currency" text DEFAULT 'UZS' NOT NULL,
	"locale" text DEFAULT 'uz' NOT NULL,
	"theme" text DEFAULT 'system' NOT NULL,
	"min_reserve" numeric(18, 2) DEFAULT 0 NOT NULL,
	"estimated_income_confidence" integer DEFAULT 50 NOT NULL,
	"notify_payments" boolean DEFAULT true NOT NULL,
	"notify_income" boolean DEFAULT true NOT NULL,
	"notify_budget" boolean DEFAULT true NOT NULL,
	"notify_risk" boolean DEFAULT true NOT NULL,
	"role" text DEFAULT 'USER' NOT NULL,
	"is_blocked" boolean DEFAULT false NOT NULL,
	"is_demo" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "users_role_check" CHECK ("users"."role" in ('USER', 'ADMIN')),
	CONSTRAINT "users_confidence_check" CHECK ("users"."estimated_income_confidence" between 0 and 100),
	CONSTRAINT "users_reserve_check" CHECK ("users"."min_reserve" >= 0)
);
--> statement-breakpoint
ALTER TABLE "accounts" ADD CONSTRAINT "accounts_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "budgets" ADD CONSTRAINT "budgets_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "budgets" ADD CONSTRAINT "budgets_category_id_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "categories" ADD CONSTRAINT "categories_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "debt_payments" ADD CONSTRAINT "debt_payments_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "debt_payments" ADD CONSTRAINT "debt_payments_debt_id_debts_id_fk" FOREIGN KEY ("debt_id") REFERENCES "public"."debts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "debts" ADD CONSTRAINT "debts_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "expected_incomes" ADD CONSTRAINT "expected_incomes_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "expected_incomes" ADD CONSTRAINT "expected_incomes_account_id_accounts_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "expected_incomes" ADD CONSTRAINT "expected_incomes_category_id_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "financial_snapshots" ADD CONSTRAINT "financial_snapshots_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "goal_contributions" ADD CONSTRAINT "goal_contributions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "goal_contributions" ADD CONSTRAINT "goal_contributions_goal_id_goals_id_fk" FOREIGN KEY ("goal_id") REFERENCES "public"."goals"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "goals" ADD CONSTRAINT "goals_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "goals" ADD CONSTRAINT "goals_account_id_accounts_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "idempotency_keys" ADD CONSTRAINT "idempotency_keys_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pending_drafts" ADD CONSTRAINT "pending_drafts_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "recurring_expenses" ADD CONSTRAINT "recurring_expenses_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "recurring_expenses" ADD CONSTRAINT "recurring_expenses_category_id_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "recurring_expenses" ADD CONSTRAINT "recurring_expenses_account_id_accounts_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "security_events" ADD CONSTRAINT "security_events_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "telegram_updates" ADD CONSTRAINT "telegram_updates_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "transactions" ADD CONSTRAINT "transactions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "transactions" ADD CONSTRAINT "transactions_account_id_accounts_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "transactions" ADD CONSTRAINT "transactions_to_account_id_accounts_id_fk" FOREIGN KEY ("to_account_id") REFERENCES "public"."accounts"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "transactions" ADD CONSTRAINT "transactions_category_id_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "transactions" ADD CONSTRAINT "transactions_recurring_id_recurring_expenses_id_fk" FOREIGN KEY ("recurring_id") REFERENCES "public"."recurring_expenses"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "transactions" ADD CONSTRAINT "transactions_expected_income_id_expected_incomes_id_fk" FOREIGN KEY ("expected_income_id") REFERENCES "public"."expected_incomes"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "accounts_user_idx" ON "accounts" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "audit_user_created_idx" ON "audit_logs" USING btree ("user_id","created_at");--> statement-breakpoint
CREATE INDEX "audit_request_idx" ON "audit_logs" USING btree ("request_id");--> statement-breakpoint
CREATE UNIQUE INDEX "budget_unique_idx" ON "budgets" USING btree ("user_id","category_id","month");--> statement-breakpoint
CREATE INDEX "categories_user_idx" ON "categories" USING btree ("user_id","type");--> statement-breakpoint
CREATE INDEX "debt_payments_debt_idx" ON "debt_payments" USING btree ("debt_id");--> statement-breakpoint
CREATE INDEX "debts_user_idx" ON "debts" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "expected_income_user_idx" ON "expected_incomes" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "snapshots_user_date_key" ON "financial_snapshots" USING btree ("user_id","snapshot_date");--> statement-breakpoint
CREATE INDEX "goal_contrib_goal_idx" ON "goal_contributions" USING btree ("goal_id");--> statement-breakpoint
CREATE INDEX "goals_user_idx" ON "goals" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "idempotency_user_key_scope" ON "idempotency_keys" USING btree ("user_id","key","scope");--> statement-breakpoint
CREATE INDEX "idempotency_expires_idx" ON "idempotency_keys" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "notifications_user_idx" ON "notifications" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "pending_drafts_user_idx" ON "pending_drafts" USING btree ("user_id","status");--> statement-breakpoint
CREATE INDEX "recurring_user_idx" ON "recurring_expenses" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "security_event_created_idx" ON "security_events" USING btree ("event","created_at");--> statement-breakpoint
CREATE INDEX "tx_user_date_idx" ON "transactions" USING btree ("user_id","date");--> statement-breakpoint
CREATE INDEX "tx_type_idx" ON "transactions" USING btree ("user_id","type");--> statement-breakpoint
CREATE UNIQUE INDEX "users_telegram_id_key" ON "users" USING btree ("telegram_id");